
// Saga Actions
export const ADD_USER = "ADD_USER";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REGISTER = "AUTH_REGISTER";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOAD = "AUTH_LOAD";

export const TEAM_CREATE = "TEAM_CREATE";
export const TEAM_JOIN = "TEAM_JOIN";

// Redux Store Actions
export const REGISTER_FORM_SET = "REGISTER_FORM_SET";
export const REGISTER_FORM_RESET = "REGISTER_FORM_RESET";

export const LOGIN_FORM_SET = "LOGIN_FORM_SET";
export const LOGIN_FORM_RESET = "LOGIN_FORM_RESET";

export const TEAM_FORM_SET = "TEAM_FORM_SET";
export const TEAM_FORM_RESET = "TEAM_FORM_RESET";

export const LESSON_EDITOR_SET = "LESSON_EDITOR_SET";
export const LESSON_EDITOR_RESET = "LESSON_EDITOR_RESET";
export const LESSON_EDITOR_CREATE = "LESSON_EDITOR_CREATE";
export const LESSON_EDITOR_UPDATE = "LESSON_EDITOR_UPDATE";
export const LESSON_EDITOR_LOAD_LESSON = "LESSON_EDITOR_LOAD_LESSON";
export const LESSON_EDITOR_STATUS_LOAD = "LESSON_EDITOR_STATUS_LOAD";
export const LESSON_EDITOR_STATUS_SUCCESS = "LESSON_EDITOR_STATUS_SUCCESS";
export const LESSON_EDITOR_STATUS_FAILURE = "LESSON_EDITOR_STATUS_FAILURE";

export const USER_SET = "USER_SET";
export const USER_RESET = "USER_RESET";
